### ISSUE TITLE
add favorites/star functionality

### ISSUE THREAD

**Issue by kleerkoat** [mflint/ios-tldr-viewer#18]
what about having a favorites list to add commands to?

**Comment by mflint** [comment]
Sounds good!

I'll code it if you help test it. Deal?

**Comment by mflint** [comment]
@kleerkoat I have some working favourites code, with iCloud sync. Mail me from the app if you'd like to join the TestFlight group. - Matthew

**Comment by kleerkoat** [comment]
deal signed and sealed! email on the way, thank you!

**Comment by mflint** [comment]
Fixed in commit 1cb08d4720d7385e8fda34ec08340af17136e9fe

**Comment by mflint** [comment]
@kleerkoat No email arrived. Can you try again, please, or DM me on Twitter `@mkflint`.
