### ISSUE TITLE
Brew-cask addition

### ISSUE THREAD

**Issue by Jahhein** [mflint/ios-tldr-viewer#19]
Add 

Uninstall given cask and remove all related files of that cask
    'Brew cask zap cask_name'

**Comment by melgu** [comment]
Please post suggestions to the main tldr GitHub page:
https://github.com/tldr-pages/tldr

You could either create pull request yourself or open an issue as inspiration for someone else to create a pull request.

**Comment by melgu** [comment]
@Jahhein I just created a pull request over at the main tldr GitHub page.

**Comment by Jahhein** [comment]
This is a very old issue I created. It seems I didn't even complete what I was writting and must've accidently still created. 

I apologize for missing your request @melgu to go to the main TLDR repository. However, thank you very much for getting it resolved still!
