### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by melgu** [mflint/ios-tldr-viewer#20]
You get the following error at the start:

> Could not unzip the download

Deleting and reinstalling doesn't help, except the app is now even more useless, because completely empty.

**Comment by mflint** [comment]
Oof, “even more useless”. That hurts! ;-)

I’m looking into it. Thanks for the email!

  Matthew

--
Matthew Flint
matthew@greenlightapps.co.uk

**Comment by melgu** [comment]
@mflint Don't get me wrong. I might have articulated myself unclear.
In working condition, I truly love your app! It's just not of much use when being completely empty after the reinstall 😉
(The 'even more useless' referred to the current state compared to an outdated index by several weeks/months).

**Comment by mflint** [comment]
Don’t worry - it’s fine. I’m just surprised that anyone actively uses the app!

It looks like a domain wasn’t renewed by the tl;dr people, and it’s being fixed. If it’s not working tomorrow, after the DNS changes propagate, I’ll try to do another fix.

Thanks for the email - I truly appreciate it :-)

  Matthew

--
Matthew Flint
matthew@greenlightapps.co.uk

**Comment by mflint** [comment]
See https://github.com/tldr-pages/tldr/issues/2253

**Comment by melgu** [comment]
I really like the app for exploring commands on the go – finding new system ones or interesting external tools.
The website is still reachable via [http://tldr-pages.github.io]() if that helps.

**Comment by melgu** [comment]
Works again!

BTW, I just realized that favorites are saved via iCloud or something, nice!
