### ISSUE TITLE
App shows commands which have been deleted/renamed

### ISSUE THREAD

**Issue by SimplyDanny** [mflint/ios-tldr-viewer#22]
Just now I noticed that the command `brew-mas` is still present in the app, although it has been renamed to `mas` [here](https://github.com/tldr-pages/tldr/commit/06a93a9b52ba260b7fba598f82b0e83380bffc21#diff-491c43f1e95226328300a9913732092a). Updating the app data didn't change anything.

Digging a little bit through the code I found two issues which might cause this bug (in combination):
* `Zip.unzipFile` just copies the files and overwrites existing ones. Files which already exist in the destination directory but are not present anymore in the ZIP archive will stay there "forever".
* The [DataSource](https://github.com/mflint/ios-tldr-viewer/blob/master/tldr-viewer/DataSource.swift) extracts the commands to present in the app from the `index.json` file but does not consider the language tag.

Now, in this concrete case: The file `brew-mas.md` still exists on the device because it has not been cleaned up somehow. This fact alone would not show it in the UI. However, `DataSource` also finds it in the `index.json` file for the `zh` language, since it has only been renamed for the primary (`en`) language. Thus, all prerequisites are fulfilled to actually show the command in the app.

**Comment by mflint** [comment]
PR merged and app submitted to Apple for review.

**Comment by SimplyDanny** [comment]
The bug may have been fixed, but the first point still holds. Namely, renamed or deleted files will remain on the device. How would you address this point?
