### ISSUE TITLE
Suggested description for ‘ls’

### ISSUE THREAD

**Issue by davidgaryesp** [mflint/ios-tldr-viewer#34]
I wish it said something like "List contents of the specified directory, or if none specified, of the current directory."

Because when I first used it with -R, I was confused about what to expect.  At that "crawling" stage, when I said "ls -R afile" then I expected it to report all occurrences of afile in the directory tree.  

I now realise (from forum help) that when used in that way, the name should be that of a directory, not a file.  Then it will find all directories/subdirectories having that name.

**Comment by mflint** [comment]
Hello @davidgaryesp,

Thank-you for taking the time to raise this issue... but this repo is for the iOS client app only. The actual content is [over here in the "tldr-pages / tldr" repo](https://github.com/tldr-pages/tldr). They'll accept pull requests there, if you're willing to make one :)

For your specific issue, maybe you're looking for [find](https://github.com/tldr-pages/tldr/blob/main/pages/common/find.md)?
