### ISSUE TITLE
Rendering issue on PowerShell dict variables

### ISSUE THREAD

**Issue by reinhart1010** [mflint/ios-tldr-viewer#36]
Hello, I'm the writer of the [`Invoke-WebRequest`](https://github.com/tldr-pages/tldr/pull/8177) tldr page.

The documentation includes placing PowerShell dictionary (e.g. `@{Foo='bar'}` inside the `tldr`'s variable container (`{{}}`) which causes the dict variable to be rendered incomplete, i.e. "`@{Foo='bar'`}" instead of "`@{Foo='bar'}`".

![telegram-cloud-photo-size-5-6296170809395360688-y](https://user-images.githubusercontent.com/17312341/182763135-e18c9d1e-d7bf-46cf-823c-2e2085f230d0.jpg)

The issue can be seen more clearly on another tldr-pages website made by myself, see reinhart1010/nix#1 for details.

![Issue in Nix](https://user-images.githubusercontent.com/17312341/182761510-accc6b57-6386-4fea-97fe-31dcc1bd545b.png)

**Comment by mflint** [comment]
Thank-you for the bug report @reinhart1010. I've added a small fix to the code, and submitted a new version to the AppStore today.
