### ISSUE TITLE
Search bar is not showing input text

### ISSUE THREAD

**Issue by Helmoes** [mflint/ios-tldr-viewer#37]
Pretty much what the title says. The screencap shows the issue.

![ezgif-3-16da1e9b01](https://user-images.githubusercontent.com/61212162/184474620-04b3083a-02c1-4f10-bde5-83be1c78c815.gif)

**Comment by mflint** [comment]
Thank-you @Helmoes. That's embarrassing. I changed the colours last week and forgot to check _dark mode_.

As a temporary workaround, it should be fine in light-mode.

I'll push a new build to Apple today.

**Comment by Helmoes** [comment]
No problem, thanks for the quick response.
I've been loving the app!

**Comment by mflint** [comment]
@Helmoes I've released an update today. Can you check it, please, and close this issue if you're happy?

**Comment by Helmoes** [comment]
Works perfectly!
